title: hola
author: %
email: your-email@domain.com
description: > 123fadsgsadha

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
